<template>
  <div class="page-wrapper">
    <header class="page-header">
      <a href="http://convert.zeto.io/coordinates" rel="self"><h1>Geographic Coordinate Converter</h1></a>
      <p>Put a list of geographic coordinates separated by linebreaks in the left textarea and copy the converted coordinates form the right textarea. You can change the format of the output format with some options.</p>
    </header>
    <aside class="page-options">
      <section>
        <h2>Input</h2>
        <p>Paste in the order <strong>latitude, longitude</strong> if providing no hemisphere letters. Format can be quite freely choosen.</p>
        <small>Input is parsed by <a href="https://github.com/gmaclennan/parse-dms">parse-dms</a>. See their <a href="https://github.com/gmaclennan/parse-dms#usage">documentation</a> for more information.</small>
      </section>
      <Option
        label="Output"
        :formats="formatsOutput"
        v-on:updateFormat="oFormat = $event">
        Output is generated by <a href="https://github.com/nerik/formatcoords">formatcoords</a>. See their <a href="https://github.com/nerik/formatcoords#formatting">documentation</a> for more information.
      </Option>
    </aside>
    <IO
      :compiledList="compiledList"
      :sample="sample"
      v-on:updateInput="input = $event" />
  </div>
</template>

<script>
  import IO from '~/components/IO.vue'
  import Option from '~/components/Option.vue'
  import { convertList } from '~/assets/scripts/utils.js'
  import parseDMS from 'parse-dms'
  import formatcoords from 'formatcoords'
  import isNull from 'lodash/isNull'

  const sample = 'N51° 30\' 0.5486" W0° 7\' 34.4503"\n51°30\'0.5486" -0°7\'34.4503"\n0°7\'34.4503"W 51°30\'0.5486"N\n51:30:0.5486N 0:7:34.4503W\nN51° 30\' 0.5486\'\' W0° 7\' 34.4503\'\'\nN51° 30.009143333333\' W0° 7.574171666666667\'\n51.500152388888885,-0.12623619444444445\n51.500152388888885 -0.12623619444444445'

  const formatsOutput = [
    { text: 'DMS – degrees minutes seconds', sample: '27° 43′ 31.796″ N 18° 1′ 27.484″ W', value: 'FFf' },
    { text: 'DMS – degrees minutes seconds', sample: '27° 43\' 31.796\'\' N 18° 1\' 27.484\'\' W', value: 'DD M\' s\'\'' },
    { text: 'Degrees decimal minutes', sample: '27° 43.52993′ N -18° 1.45806′ W', value: 'Ff' },
    { text: 'DD – Decimal degrees', sample: '27.725499° N 18.024301° W', value: 'f' },
    { text: 'DD – Decimal degrees', sample: '27.725499 18.024301', value: 'd' }
  ]

  export default {
    data: function () {
      return {
        oFormat: null,
        formatsOutput,
        input: null,
        sample
      }
    },
    computed: {
      compiledList: function () {
        const { input, oFormat } = this

        if (isNull(input) || input.length === 0 || isNull(oFormat)) {
          return []
        }

        return convertList(input, line => {
          const coords = parseDMS(line)
          return formatcoords([coords.lat, coords.lon]).format(oFormat)
        })
      }
    },
    components: {
      IO,
      Option
    }
  }
</script>

<style lang="scss" scoped>
  @import "~@/assets/style/global";

  .page-wrapper {
    width: calc(100vw - #{$spacing * 2});
    max-width: 1120px;
    margin: $spacing;
  }
</style>
